// Written by AI

export const cityEnBnMapping = {
  Dhaka: "ঢাকা",
  Biman_Bandar: "বিমানবন্দর",
  Gafargaon: "গফরগাঁও",
  Mymensingh: "ময়মনসিংহ",
  Narundi: "নারুন্দি",
  Jamalpur_Town: "জামালপুর টাউন",
  Kendua_Bazar: "কেন্দুয়া বাজার",
  Sarishabari: "সরিষাবাড়ী",
  Tarakandi: "তারাকান্দি",
  Piyarpur: "পিয়ারপুর",
  Nandina: "নান্দিনা",
  Melandah_Bazar: "মেলান্দহ বাজার",
  Islampur_Bazar: "ইসলামপুর বাজার",
  Dewanganj_Bazar: "দেওয়ানগঞ্জ বাজার",
  Rajshahi: "রাজশাহী",
  Chapainawabganj: "চাঁপাইনবাবগঞ্জ",
  Kakonhat: "কাকনহাট",
  Lolitnagar: "ললিতনগর",
  Amnura_Bypass: "আমনুরা বাইপাস",
  Abdulpur: "আব্দুলপুর",
  Natore: "নাটোর",
  Madhnagar: "মাধনগর",
  Ahsanganj: "আহসানগঞ্জ",
  Santahar: "সান্তাহার",
  Akkelpur: "আক্কেলপুর",
  Joypurhat: "জয়পুরহাট",
  Panchbibi: "পাঁচবিবি",
  Birampur: "বিরামপুর",
  Fulbari: "ফুলবাড়ী",
  Parbatipur: "পার্বতীপুর",
  Chirirbandar: "চিরিরবন্দর",
  Dinajpur: "দিনাজপুর",
  Setabganj: "সেতাবগঞ্জ",
  Pirganj: "পীরগঞ্জ",
  Shibganj: "শিবগঞ্জ",
  Thakurgaon_Road: "ঠাকুরগাঁও রোড",
  Ruhia: "রুহিয়া",
  Kismat: "কিসমত",
  Panchagarh: "পঞ্চগড়",
  Saidpur: "সৈয়দপুর",
  Nilphamari: "নীলফামারী",
  Domar: "ডোমার",
  Chilahati: "চিলাহাটি",
  Hili: "হিলি",
  Benapole: "বেনাপোল",
  Jhikargacha: "ঝিকরগাছা",
  Jashore: "যশোর",
  Mubarakganj: "মোবারকগঞ্জ",
  Kotchandpur: "কোটচাঁদপুর",
  Darshana_Halt: "দর্শনা হল্ট",
  Chuadanga: "চুয়াডাঙ্গা",
  Alamdanga: "আলমডাঙ্গা",
  Poradaha: "পোড়াদহ",
  Kushtia_Court: "কুষ্টিয়া কোর্ট",
  Khoksha: "খোকসা",
  Kalukhali: "কালুখালী",
  Rajbari: "রাজবাড়ী",
  Faridpur: "ফরিদপুর",
  Bhanga: "ভাঙ্গা",
  Joydebpur: "জয়দেবপুর",
  Sreepur: "শ্রীপুর",
  Chattogram: "চট্টগ্রাম",
  Bhatiary: "ভাটিয়ারী",
  Feni: "ফেনী",
  Laksam: "লাকসাম",
  Cumilla: "কুমিল্লা",
  Akhaura: "আখাউড়া",
  Bhairab_Bazar: "ভৈরব বাজার",
  Sararchar: "সরারচর",
  Kishorganj: "কিশোরগঞ্জ",
  Atharabari: "আঠারবাড়ী",
  Gouripur_Myn: "গৌরীপুর",
  "Ishwardi Bypass": "ঈশ্বরদী বাইপাস",
  Bogura: "বগুড়া",
  Mahimaganj: "মহিমাগঞ্জ",
  Bonar_Para: "বোনারপাড়া",
  Gaibandha: "গাইবান্ধা",
  Kaunia: "কাউনিয়া",
  Lalmonirhat: "লালমনিরহাট",
  Kankina: "কাকিনা",
  Tushbhandar: "তুষভান্ডার",
  Bhotmari: "ভোটমারী",
  Hatibandha: "হাতীবান্ধা",
  Barkhata: "বারখাতা",
  Baura: "বাউরা",
  Patgram: "পাটগ্রাম",
  Burimari: "বুড়িমারী",
  Kumira: "কুমিরা",
  Hasanpur: "হাসানপুর",
  Nangolkot: "নাঙ্গলকোট",
  Shashidal: "শশীদল",
  Quasba: "কসবা",
  Brahmanbaria: "ব্রাহ্মণবাড়িয়া",
  Methikanda: "মেথিকান্দা",
  Narsingdi: "নরসিংদী",
  Ishwardi_Bypass: "ঈশ্বরদী বাইপাস",
  Azim_Nagar: "আজিমনগর",
  Noapara: "নওয়াপাড়া",
  Mirpur: "মিরপুর",
  Bheramara: "ভেড়ামারা",
  Ishwardi: "ঈশ্বরদী",
  Chatmohar: "চাটমোহর",
  Boral_Bridge: "বড়াল ব্রিজ",
  Ullapara: "উল্লাপাড়া",
  "SH M Monsur Ali": "শহীদ এম. মনসুর আলী",
  Ibrahimabad: "ইব্রাহিমাবাদ",
  Tangail: "টাঙ্গাইল",
  Khulna: "খুলনা",
  "Cox's Bazar": "কক্সবাজার",
  Dhalarchar: "ঢালারচর",
  Badherhat: "বাঘেরহাট",
  Kashinathpur: "কাশিনাথপুর",
  Sathia_Rajapur: "সাঁথিয়া রাজাপুর",
  Tantibandha: "তাঁতিবন্ধা",
  Dublia: "দুবলিয়া",
  Raghabpur: "রাঘবপুর",
  Pabna: "পাবনা",
  Tebunia: "টেবুনিয়া",
  Dashuria: "দাশুড়িয়া",
  Majhgram: "মাঝগ্রাম",
  Arani: "আড়ানী",
  Sardah_Road: "সারদাহ রোড",
  Jamtail: "জামতৈল",
  Shyamgonj: "শ্যামগঞ্জ",
  Netrakona: "নেত্রকোণা",
  Thakrokona: "ঠাকুরকোনা",
  Barhatta: "বারহাট্টা",
  Singia: "সিঙ্গিয়া",
  Narail: "নড়াইল",
  Lohagora: "লোহাগড়া",
  Kashiani: "কাশিয়ানী",
  Bhanga_Junction: "ভাঙ্গা জংশন",
  Bidyaganj: "বিদ্যাগঞ্জ",
  Jaforshahi: "জাফরশাহী",
  Jagannathgonj_Bazar: "জগন্নাথগঞ্জ বাজার",
  Hemnagar: "হেমনগর",
  Bhuapur: "ভূঞাপুর",
  Kaoraid: "কাওরাইদ",
  Ashuganj: "আশুগঞ্জ",
  Azampur: "আজমপুর",
  Mukundapur: "মুকুন্দপুর",
  Harashpur: "হারাশপুর",
  Montola: "মনতলা",
  Nayapara: "নয়াপাড়া",
  Shahaji_Bazar: "শাহাজীবাজার",
  Shaistaganj: "শায়েস্তাগঞ্জ",
  Sreemangal: "শ্রীমঙ্গল",
  Bhanugach: "ভানুগাছ",
  Kulaura: "কুলাউড়া",
  Maijgaon: "মাইজগাঁও",
  Sylhet: "সিলেট",
  Shamshernagar: "শমশেরনগর",
  Manmathapur: "মানমথপুর",
  Kawgaon: "কাওগাঁও",
  Kanchan_Junction: "কাঞ্চন জংশন",
  Mongalpur: "মঙ্গলপুর",
  Sultanpur: "সুলতানপুর",
  Bhomradah: "ভোমরাদহ",
  Akhanagar: "আখানগর",
  Nayaniburuj: "নয়নীবুরুজ",
  Safdarpur: "সাফদারপুর",
  Paksey: "পাকশী",
  Kuliarchar: "কুলিয়ারচর",
  Bajitpur: "বাজিতপুর",
  Manikkhali: "মানিকখালী",
  Gachihata: "গচিহাটা",
  Sonatola: "সোনাতলা",
  Bamondanga: "বামনডাঙ্গা",
  Pirgacha: "পীরগাছা",
  Teesta_Junction: "তিস্তা জংশন",
  Aditmari: "আদিতমারী",
  Badarganj: "বদরগঞ্জ",
  Rangpur: "রংপুর",
  Kurigram: "কুড়িগ্রাম",
  Mahendranagar: "মহেন্দ্রনগর",
  Mirbagh: "মীরবাগ",
  Shyampur: "শ্যামপুর",
  Kholahati: "খোলাহাটী",
  Birol: "বিরল",
  Sreenagar: "শ্রীনগর",
  Mawa: "মাওয়া",
  Padma: "পদ্মা",
  Shibchar: "শিবচর",
  Pukuria: "পুকুরিয়া",
  Talma: "তালমা",
  Amirabad: "আমিরাবাদ",
  Pachuria: "পাচুরিয়া",
  Pangsha: "পাংশা",
  Kumarkhali: "কুমারখালী",
  Gunabati: "গুণবতী",
  Chitoshi_Road: "চিতোষী রোড",
  Meher: "মেহের",
  Hajiganj: "হাজীগঞ্জ",
  Modhu_Road: "মধু রোড",
  Chandpur_Court: "চাঁদপুর কোর্ট",
  Chandpur: "চাঁদপুর",
  Mohanganj: "মোহনগঞ্জ",
  Muladhuli: "মূলাডুলি",
  Baramchal: "বরমচাল",
  Ramu: "রামু",
  ISLAMABAD: "ইসলামাবাদ",
  Dulahazara: "দুলাহাজারা",
  Chakaria: "চকরিয়া",
  HARBANG: "হারবাং",
  LOHAGARA: "লোহাগাড়া",
  Satkania: "সাতকানিয়া",
  Dohazari: "দোহাজারী",
  Patiya: "পটিয়া",
  GOMDANDI: "গোমদণ্ডী",
  Sholoshohor: "ষোলশহর",
  Talora: "তালোড়া",
  Muksudpur: "মুকসুদপুর",
  Noakhali: "নোয়াখালী",
  Harinarayanpur: "হরিনারায়ণপুর",
  Maijdee_Court: "মাইজদী কোর্ট",
  Maijdee: "মাইজদী",
  Chowmuhani: "চৌমুহনী",
  Bazra: "বজরা",
  Sonaimuri: "সোনাইমুড়ী",
  Bipulashar: "বিপুলাসার",
  Natherpetua: "নাথেরপেটুয়া",
  Khila: "খিলা",
  Daulatganj: "দৌলতগঞ্জ",
  Janali_Hat: "জানালী হাট",
  SH_M_Monsur_Ali: "শহীদ এম মনসুর আলী",
  Daulatpur: "দৌলতপুর",
  Sirajganj_Bazar: "সিরাজগঞ্জ বাজার",
  Sirajganjraipur: "সিরাজগঞ্জ রায়পুর",
  SOYDABAD: "সয়দাবাদ",
  Hi_Tech_City: "হাই-টেক সিটি",
  Jamalganj: "জামালগঞ্জ",
  Gobra: "গোবরা",
  Borashi: "বোরাশী",
  Gopalganj: "গোপালগঞ্জ",
  Chandradighalia: "চন্দ্রদিঘলিয়া",
  Choto_Bahirbag: "ছোট বাহিরবাগ",
  Chapta: "চাপটা",
  Boalmari_Bazar: "বোয়ালমারী বাজার",
  Madhukhali: "মধুখালী",
  Baharpur: "বাহারপুর",
  Naliagram: "নলিয়াগ্রাম",
  Khatra: "খাটরা",
  Maijdi_Court: "মাইজদী কোর্ট",
  Choumuhani: "চৌমুহনী",
  Bajra: "বজরা",

  // Added for stations missing from all-trips lookup
  Amirganj: "আমিরগঞ্জ",
  Arikhola: "আড়িখোলা",
  Badiakhali: "বাদিয়াখালী",
  Bhatera: "ভাটেরা",
  Bhatshala: "ভাতশালা",
  Chatiyan: "ছাতিয়াইন",
  Chinki_Astana: "চিনকিআস্তানা",
  Chokhapon: "ছকাপন",
  "Cox's_Bazar": "কক্সবাজার",
  Daulatkandi: "দৌলতকান্দি",
  Fenchuganj: "ফেঞ্চুগঞ্জ",
  Gangasagar: "গঙ্গাসাগর",
  Ghorashal: "ঘোড়াশাল",
  Ghorashal_Flag: "ঘোড়াশাল ফ্ল্যাগ",
  Hatubhanga: "হাটুভাঙ্গা",
  "Hi-Tech_City": "হাই-টেক সিটি",
  Imambari: "ইমামবাড়ী",
  Itakhola: "ইটাখোলা",
  Jinardi: "জিনারদী",
  Khanabari: "খানাবাড়ী",
  Langla: "লংলা",
  Laskarpur: "লস্করপুর",
  Mandabag: "মন্দবাগ",
  Mantala: "মনতলা",
  Manu: "মনু",
  Merasani: "মেরাসানি",
  Mirzapur: "মির্জাপুর",
  Mogla_Bazar: "মোগলাবাজার",
  Nowapara: "নোয়াপাড়া",
  Paghachang: "পাঘাচং",
  Pahartali: "পাহাড়তলী",
  Pubail: "পুবাইল",
  Rajapur: "রাজাপুর",
  Rashidpur: "রশিদপুর",
  Sadar_Rasulpur: "সদর রসুলপুর",
  Saldanadi: "সালদানদী",
  Satgaon: "সাতগাঁও",
  Satiajuri: "সাটিয়াজুড়ি",
  Shahapur: "শাহপুর",
  Shamsher_Nagar: "শমশেরনগর",
  Singerbil: "সিঙ্গারবিল",
  Sitakunda: "সীতাকুন্ড",
  Srinidhi: "শ্রীনিধি",
  Talshahar: "তালশহর",
  Tejgaon: "তেজগাঁও",
  Teliapara: "তেলিয়াপাড়া",
  Tilagaon: "টিলাগাঁও",
  Tongi: "টঙ্গী জংশন",
};
