// AI generated

export const trainNameEnBnMapping = {
  "AGHNIBINA EXPRESS": "অগ্নিবীণা এক্সপ্রেস",
  "BANALATA EXPRESS": "বনলতা এক্সপ্রেস",
  "BANGLABANDHA EXPRESS": "বাংলাবান্ধা এক্সপ্রেস",
  "BARENDRA EXPRESS": "বরেন্দ্র এক্সপ্রেস",
  "BENAPOLE EXPRESS": "বেনাপোল এক্সপ্রেস",
  "BHRAMMAPUTRA EXPRESS": "ব্রহ্মপুত্র এক্সপ্রেস",
  "BIJOY EXPRESS": "বিজয় এক্সপ্রেস",
  "BURIMARI COMMUTER": "বুড়িমারী কমিউটার",
  "BURIMARI EXPRESS": "বুড়িমারী এক্সপ্রেস",
  "CHAPAINAWABGANJ SHUTTLE": "চাঁপাইনবাবগঞ্জ শাটল",
  "CHATTALA EXPRESS": "চট্টলা এক্সপ্রেস",
  "CHATTOGRAM MAIL": "চট্টগ্রাম মেইল",
  "CHILAHATI EXPRESS": "চিলাহাটি এক্সপ্রেস",
  "CHITRA EXPRESS": "চিত্রা এক্সপ্রেস",
  "COXS BAZAR EXPRESS": "কক্সবাজার এক্সপ্রেস",
  "DHAKA MAIL": "ঢাকা মেইল",
  "DHALARCHAR EXPRESS": "ঢালারচর এক্সপ্রেস",
  "DHUMKETU EXPRESS": "ধূমকেতু এক্সপ্রেস",
  "DOLONCHAPA EXPRESS": "দোলনচাঁপা এক্সপ্রেস",
  "DRUTOJAN EXPRESS": "দ্রুতযান এক্সপ্রেস",
  "EGAROSINDHUR GODHULI": "এগারসিন্দুর গোধূলি",
  "EGAROSINDHUR PROVATI": "এগারসিন্দুর প্রভাতী",
  "EKOTA EXPRESS": "একতা এক্সপ্রেস",
  "HAWR EXPRESS": "হাওর এক্সপ্রেস",
  "JAHANABAD EXPRESS": "জাহানাবাদ এক্সপ্রেস",
  "JALALABAD MAIL": "জালালাবাদ মেইল",
  "JAMALPUR EXPRESS": "জামালপুর এক্সপ্রেস",
  "JAMUNA EXPRESS": "যমুনা এক্সপ্রেস",
  "JAYENTIKA EXPRESS": "জয়ন্তিকা এক্সপ্রেস",
  "KALNI EXPRESS": "কালনী এক্সপ্রেস",
  "KANCHON INTERCITY COMMUTER": "কাঞ্চন আন্তঃনগর কমিউটার",
  "KAPOTAKSHA EXPRESS": "কপোতাক্ষ এক্সপ্রেস",
  "KARNAPHULI COMMUTER": "কর্ণফুলী কমিউটার",
  "KISHORGANJ EXPRESS": "কিশোরগঞ্জ এক্সপ্রেস",
  "KOROTOA EXPRESS": "করতোয়া এক্সপ্রেস",
  "KURIGRAM EXPRESS": "কুড়িগ্রাম এক্সপ্রেস",
  "LALMONI COMMUTER": "লালমনি কমিউটার",
  "LALMONI EXPRESS": "লালমনি এক্সপ্রেস",
  "MADHUMATI EXPRESS": "মধুমতি এক্সপ্রেস",
  "MAHANAGAR GODHULI": "মহানগর গোধূলি",
  "MAHANAGAR PROVATI": "মহানগর প্রভাতী",
  "MEGHNA EXPRESS": "মেঘনা এক্সপ্রেস",
  "MOHANAGAR EXPRESS": "মহানগর এক্সপ্রেস",
  "MOHONGANJ EXPRESS": "মোহনগঞ্জ এক্সপ্রেস",
  "NILSAGAR EXPRESS": "নীলসাগর এক্সপ্রেস",
  "NOAKHALI MAIL": "নোয়াখালী মেইল",
  "PADMA EXPRESS": "পদ্মা এক্সপ্রেস",
  "PAHARIKA EXPRESS": "পাহাড়িকা এক্সপ্রেস",
  "PANCHAGARH EXPRESS": "পঞ্চগড় এক্সপ্রেস",
  "PARABAT EXPRESS": "পারাবত এক্সপ্রেস",
  "PARJOTAK EXPRESS": "পর্যটক এক্সপ্রেস",
  "PROBAL EXPRESS": "প্রবাল এক্সপ্রেস",
  "RAJSHAHI COMMUTER": "রাজশাহী কমিউটার",
  "RANGPUR EXPRESS": "রংপুর এক্সপ্রেস",
  "RUPOSHI BANGLA EXPRESS": "রূপসী বাংলা এক্সপ্রেস",
  "RUPSHA EXPRESS": "রূপসা এক্সপ্রেস",
  "SAGARDARI EXPRESS": "সাগরদাঁড়ি এক্সপ্রেস",
  "SAGARIKA COMMUTER": "সাগরিকা কমিউটার",
  "SHAIKAT EXPRESS": "সৈকত এক্সপ্রেস",
  "SILKCITY EXPRESS": "সিল্কসিটি এক্সপ্রেস",
  "SIMANTA EXPRESS": "সীমান্ত এক্সপ্রেস",
  "SIRAJGANJ EXPRESS": "সিরাজগঞ্জ এক্সপ্রেস",
  "SONAR BANGLA EXPRESS": "সোনার বাংলা এক্সপ্রেস",
  "SUBORNO EXPRESS": "সুবর্ণ এক্সপ্রেস",
  "SUNDARBAN EXPRESS": "সুন্দরবন এক্সপ্রেস",
  "SURMA MAIL": "সুরমা মেইল",
  "TISTA EXPRESS": "তিস্তা এক্সপ্রেস",
  "TITAS COMMUTER": "তিতাস কমিউটার",
  "TITUMIR EXPRESS": "তিতুমীর এক্সপ্রেস",
  "TUNGIPARA EXPRESS": "টুঙ্গিপাড়া এক্সপ্রেস",
  TURNA: "তূর্ণা",
  "UDAYAN EXPRESS": "উদয়ন এক্সপ্রেস",
  "UPABAN EXPRESS": "উপবন এক্সপ্রেস",
  "UPAKUL EXPRESS": "উপকূল এক্সপ্রেস",
};
