// This file is auto-generated by step-y-trainDataSummaryForSearch.js
// Do not edit this file manually

export const trainDataSummary = [
  {
    "name": "aghnibina express",
    "forwardPath": "Dhaka to Tarakandi",
    "forwardTrainNumber": "735",
    "reversePath": "Tarakandi to Dhaka",
    "reverseTrainNumber": "736"
  },
  {
    "name": "banalata express",
    "forwardPath": "Dhaka to Chapainawabganj",
    "forwardTrainNumber": "791",
    "reversePath": "Chapainawabganj to Dhaka",
    "reverseTrainNumber": "792"
  },
  {
    "name": "banglabandha express",
    "forwardPath": "Rajshahi to Panchagarh",
    "forwardTrainNumber": "803",
    "reversePath": "Panchagarh to Rajshahi",
    "reverseTrainNumber": "804"
  },
  {
    "name": "barendra express",
    "forwardPath": "Rajshahi to Chilahati",
    "forwardTrainNumber": "731",
    "reversePath": "Chilahati to Rajshahi",
    "reverseTrainNumber": "732"
  },
  {
    "name": "benapole express",
    "forwardPath": "Benapole to Dhaka",
    "forwardTrainNumber": "795",
    "reversePath": "Dhaka to Benapole",
    "reverseTrainNumber": "796"
  },
  {
    "name": "bhrammaputra express",
    "forwardPath": "Dhaka to Dewanganj_Bazar",
    "forwardTrainNumber": "743",
    "reversePath": "Dewanganj_Bazar to Dhaka",
    "reverseTrainNumber": "744"
  },
  {
    "name": "bijoy express",
    "forwardPath": "Chattogram to Jamalpur_Town",
    "forwardTrainNumber": "785",
    "reversePath": "Jamalpur_Town to Chattogram",
    "reverseTrainNumber": "786"
  },
  {
    "name": "burimari commuter",
    "forwardPath": "Lalmonirhat to Burimari",
    "forwardTrainNumber": "65",
    "reversePath": "Burimari to Lalmonirhat",
    "reverseTrainNumber": "66"
  },
  {
    "name": "burimari express",
    "forwardPath": "Dhaka to Burimari",
    "forwardTrainNumber": "809",
    "reversePath": "Lalmonirhat to Dhaka",
    "reverseTrainNumber": "810"
  },
  {
    "name": "chapainawabganj shuttle",
    "forwardPath": "Rajshahi to Chapainawabganj",
    "forwardTrainNumber": "109",
    "reversePath": "Chapainawabganj to Rajshahi",
    "reverseTrainNumber": "110"
  },
  {
    "name": "chattala express",
    "forwardPath": "Chattogram to Dhaka",
    "forwardTrainNumber": "801",
    "reversePath": "Dhaka to Chattogram",
    "reverseTrainNumber": "802"
  },
  {
    "name": "chilahati express",
    "forwardPath": "Dhaka to Chilahati",
    "forwardTrainNumber": "805",
    "reversePath": "Chilahati to Dhaka",
    "reverseTrainNumber": "806"
  },
  {
    "name": "chitra express",
    "forwardPath": "Khulna to Dhaka",
    "forwardTrainNumber": "763",
    "reversePath": "Dhaka to Khulna",
    "reverseTrainNumber": "764"
  },
  {
    "name": "coxs bazar express",
    "forwardPath": "Cox's Bazar to Dhaka",
    "forwardTrainNumber": "813",
    "reversePath": "Dhaka to Cox's Bazar",
    "reverseTrainNumber": "814"
  },
  {
    "name": "dhalarchar express",
    "forwardPath": "Dhalarchar to Rajshahi",
    "forwardTrainNumber": "779",
    "reversePath": "Rajshahi to Dhalarchar",
    "reverseTrainNumber": "780"
  },
  {
    "name": "dhumketu express",
    "forwardPath": "Dhaka to Rajshahi",
    "forwardTrainNumber": "769",
    "reversePath": "Rajshahi to Dhaka",
    "reverseTrainNumber": "770"
  },
  {
    "name": "dolonchapa express",
    "forwardPath": "Santahar to Panchagarh",
    "forwardTrainNumber": "767",
    "reversePath": "Panchagarh to Santahar",
    "reverseTrainNumber": "768"
  },
  {
    "name": "drutojan express",
    "forwardPath": "Dhaka to Panchagarh",
    "forwardTrainNumber": "757",
    "reversePath": "Panchagarh to Dhaka",
    "reverseTrainNumber": "758"
  },
  {
    "name": "egarosindhur godhuli",
    "forwardPath": "Dhaka to Kishorganj",
    "forwardTrainNumber": "749",
    "reversePath": "Kishorganj to Dhaka",
    "reverseTrainNumber": "750"
  },
  {
    "name": "egarosindhur provati",
    "forwardPath": "Dhaka to Kishorganj",
    "forwardTrainNumber": "737",
    "reversePath": "Kishorganj to Dhaka",
    "reverseTrainNumber": "738"
  },
  {
    "name": "ekota express",
    "forwardPath": "Dhaka to Panchagarh",
    "forwardTrainNumber": "705",
    "reversePath": "Panchagarh to Dhaka",
    "reverseTrainNumber": "706"
  },
  {
    "name": "hawr express",
    "forwardPath": "Dhaka to Mohanganj",
    "forwardTrainNumber": "777",
    "reversePath": "Mohanganj to Dhaka",
    "reverseTrainNumber": "778"
  },
  {
    "name": "jahanabad express",
    "forwardPath": "Khulna to Dhaka",
    "forwardTrainNumber": "825",
    "reversePath": "Dhaka to Khulna",
    "reverseTrainNumber": "826"
  },
  {
    "name": "jamalpur express",
    "forwardPath": "Dhaka to Bhuapur",
    "forwardTrainNumber": "799",
    "reversePath": "Bhuapur to Dhaka",
    "reverseTrainNumber": "800"
  },
  {
    "name": "jamuna express",
    "forwardPath": "Dhaka to Tarakandi",
    "forwardTrainNumber": "745",
    "reversePath": "Tarakandi to Dhaka",
    "reverseTrainNumber": "746"
  },
  {
    "name": "jayentika express",
    "forwardPath": "Dhaka to Sylhet",
    "forwardTrainNumber": "717",
    "reversePath": "Sylhet to Dhaka",
    "reverseTrainNumber": "718"
  },
  {
    "name": "kalni express",
    "forwardPath": "Dhaka to Sylhet",
    "forwardTrainNumber": "773",
    "reversePath": "Sylhet to Dhaka",
    "reverseTrainNumber": "774"
  },
  {
    "name": "kanchon intercity commuter",
    "forwardPath": "Parbatipur to Panchagarh",
    "forwardTrainNumber": "41",
    "reversePath": "Panchagarh to Parbatipur",
    "reverseTrainNumber": "42"
  },
  {
    "name": "kapotaksha express",
    "forwardPath": "Khulna to Rajshahi",
    "forwardTrainNumber": "715",
    "reversePath": "Rajshahi to Khulna",
    "reverseTrainNumber": "716"
  },
  {
    "name": "kishorganj express",
    "forwardPath": "Dhaka to Kishorganj",
    "forwardTrainNumber": "781",
    "reversePath": "Kishorganj to Dhaka",
    "reverseTrainNumber": "782"
  },
  {
    "name": "korotoa express",
    "forwardPath": "Santahar to Burimari",
    "forwardTrainNumber": "713",
    "reversePath": "Burimari to Santahar",
    "reverseTrainNumber": "714"
  },
  {
    "name": "kurigram express",
    "forwardPath": "Dhaka to Kurigram",
    "forwardTrainNumber": "797",
    "reversePath": "Kurigram to Dhaka",
    "reverseTrainNumber": "798"
  },
  {
    "name": "lalmoni commuter",
    "forwardPath": "Lalmonirhat to Birol",
    "forwardTrainNumber": "61",
    "reversePath": "Birol to Lalmonirhat",
    "reverseTrainNumber": "62"
  },
  {
    "name": "lalmoni express",
    "forwardPath": "Dhaka to Lalmonirhat",
    "forwardTrainNumber": "751",
    "reversePath": "Lalmonirhat to Dhaka",
    "reverseTrainNumber": "752"
  },
  {
    "name": "madhumati express",
    "forwardPath": "Dhaka to Rajshahi",
    "forwardTrainNumber": "755",
    "reversePath": "Rajshahi to Dhaka",
    "reverseTrainNumber": "756"
  },
  {
    "name": "meghna express",
    "forwardPath": "Chattogram to Chandpur",
    "forwardTrainNumber": "729",
    "reversePath": "Chandpur to Chattogram",
    "reverseTrainNumber": "730"
  },
  {
    "name": "mohanagar express",
    "forwardPath": "Chattogram to Dhaka",
    "forwardTrainNumber": "721",
    "reversePath": "Dhaka to Chattogram",
    "reverseTrainNumber": "722"
  },
  {
    "name": "mohonganj express",
    "forwardPath": "Dhaka to Mohanganj",
    "forwardTrainNumber": "789",
    "reversePath": "Mohanganj to Dhaka",
    "reverseTrainNumber": "790"
  },
  {
    "name": "nilsagar express",
    "forwardPath": "Dhaka to Chilahati",
    "forwardTrainNumber": "765",
    "reversePath": "Chilahati to Dhaka",
    "reverseTrainNumber": "766"
  },
  {
    "name": "padma express",
    "forwardPath": "Dhaka to Rajshahi",
    "forwardTrainNumber": "759",
    "reversePath": "Rajshahi to Dhaka",
    "reverseTrainNumber": "760"
  },
  {
    "name": "paharika express",
    "forwardPath": "Chattogram to Sylhet",
    "forwardTrainNumber": "719",
    "reversePath": "Sylhet to Chattogram",
    "reverseTrainNumber": "720"
  },
  {
    "name": "panchagarh express",
    "forwardPath": "Dhaka to Panchagarh",
    "forwardTrainNumber": "793",
    "reversePath": "Panchagarh to Dhaka",
    "reverseTrainNumber": "794"
  },
  {
    "name": "parabat express",
    "forwardPath": "Dhaka to Sylhet",
    "forwardTrainNumber": "709",
    "reversePath": "Sylhet to Dhaka",
    "reverseTrainNumber": "710"
  },
  {
    "name": "parjotak express",
    "forwardPath": "Cox's Bazar to Dhaka",
    "forwardTrainNumber": "815",
    "reversePath": "Dhaka to Cox's Bazar",
    "reverseTrainNumber": "816"
  },
  {
    "name": "probal express",
    "forwardPath": "Cox's Bazar to Chattogram",
    "forwardTrainNumber": "822",
    "reversePath": "Chattogram to Cox's Bazar",
    "reverseTrainNumber": "823"
  },
  {
    "name": "rangpur express",
    "forwardPath": "Dhaka to Rangpur",
    "forwardTrainNumber": "771",
    "reversePath": "Rangpur to Dhaka",
    "reverseTrainNumber": "772"
  },
  {
    "name": "ruposhi bangla express",
    "forwardPath": "Benapole to Dhaka",
    "forwardTrainNumber": "827",
    "reversePath": "Dhaka to Benapole",
    "reverseTrainNumber": "828"
  },
  {
    "name": "rupsha express",
    "forwardPath": "Khulna to Chilahati",
    "forwardTrainNumber": "727",
    "reversePath": "Chilahati to Khulna",
    "reverseTrainNumber": "728"
  },
  {
    "name": "sagardari express",
    "forwardPath": "Khulna to Rajshahi",
    "forwardTrainNumber": "761",
    "reversePath": "Rajshahi to Khulna",
    "reverseTrainNumber": "762"
  },
  {
    "name": "shaikat express",
    "forwardPath": "Chattogram to Cox's Bazar",
    "forwardTrainNumber": "821",
    "reversePath": "Cox's Bazar to Chattogram",
    "reverseTrainNumber": "824"
  },
  {
    "name": "silkcity express",
    "forwardPath": "Dhaka to Rajshahi",
    "forwardTrainNumber": "753",
    "reversePath": "Rajshahi to Dhaka",
    "reverseTrainNumber": "754"
  },
  {
    "name": "simanta express",
    "forwardPath": "Khulna to Chilahati",
    "forwardTrainNumber": "747",
    "reversePath": "Chilahati to Khulna",
    "reverseTrainNumber": "748"
  },
  {
    "name": "sirajganj express",
    "forwardPath": "Sirajganj_Bazar to Dhaka",
    "forwardTrainNumber": "775",
    "reversePath": "Dhaka to Sirajganj_Bazar",
    "reverseTrainNumber": "776"
  },
  {
    "name": "sonar bangla express",
    "forwardPath": "Chattogram to Dhaka",
    "forwardTrainNumber": "787",
    "reversePath": "Dhaka to Chattogram",
    "reverseTrainNumber": "788"
  },
  {
    "name": "suborno express",
    "forwardPath": "Chattogram to Dhaka",
    "forwardTrainNumber": "701",
    "reversePath": "Dhaka to Chattogram",
    "reverseTrainNumber": "702"
  },
  {
    "name": "sundarban express",
    "forwardPath": "Khulna to Dhaka",
    "forwardTrainNumber": "725",
    "reversePath": "Dhaka to Khulna",
    "reverseTrainNumber": "726"
  },
  {
    "name": "tista express",
    "forwardPath": "Dhaka to Dewanganj_Bazar",
    "forwardTrainNumber": "707",
    "reversePath": "Dewanganj_Bazar to Dhaka",
    "reverseTrainNumber": "708"
  },
  {
    "name": "titumir express",
    "forwardPath": "Rajshahi to Chilahati",
    "forwardTrainNumber": "733",
    "reversePath": "Chilahati to Rajshahi",
    "reverseTrainNumber": "734"
  },
  {
    "name": "tungipara express",
    "forwardPath": "Gobra to Rajshahi",
    "forwardTrainNumber": "783",
    "reversePath": "Rajshahi to Gobra",
    "reverseTrainNumber": "784"
  },
  {
    "name": "turna",
    "forwardPath": "Chattogram to Dhaka",
    "forwardTrainNumber": "741",
    "reversePath": "Dhaka to Chattogram",
    "reverseTrainNumber": "742"
  },
  {
    "name": "udayan express",
    "forwardPath": "Chattogram to Sylhet",
    "forwardTrainNumber": "723",
    "reversePath": "Sylhet to Chattogram",
    "reverseTrainNumber": "724"
  },
  {
    "name": "upaban express",
    "forwardPath": "Dhaka to Sylhet",
    "forwardTrainNumber": "739",
    "reversePath": "Sylhet to Dhaka",
    "reverseTrainNumber": "740"
  },
  {
    "name": "upakul express",
    "forwardPath": "Noakhali to Dhaka",
    "forwardTrainNumber": "711",
    "reversePath": "Dhaka to Noakhali",
    "reverseTrainNumber": "712"
  }
] as const;